

name: ðŸ‘ï¸Secret

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      repo:
        required: false
        type: string
        default: 'dev'
    outputs:
      SETTINGS_LOCATION:
        value: ${{ jobs.secret.outputs.output0 }}
      TOKEN:
        value: ${{ jobs.secret.outputs.output1 }}
      PYPI_API_TOKEN:
        value: ${{ jobs.secret.outputs.output2 }}
      DOCKER_USERNAME:
        value: ${{ jobs.secret.outputs.output3 }}
      DOCKER_HUB_ACCESS_TOKEN:
        value: ${{ jobs.secret.outputs.output4 }} 
      GITLAB:
        value: ${{ jobs.secret.outputs.output5 }} 
      CODEBERG:
        value: ${{ jobs.secret.outputs.output6 }} 

jobs:

  secret:
    runs-on: ubuntu-latest
    outputs:
      output0: ${{ steps.op-load-secrets.outputs.SETTINGS_LOCATION }}
      output1: ${{ steps.op-load-secrets.outputs.TOKEN }}
      output2: ${{ steps.op-load-secrets.outputs.PYPI_API_TOKEN }}
      output3: ${{ steps.op-load-secrets.outputs.DOCKER_USERNAME }}
      output4: ${{ steps.op-load-secrets.outputs.DOCKER_HUB_ACCESS_TOKEN }}
      output5: ${{ steps.op-load-secrets.outputs.GITLAB }}
      output6: ${{ steps.op-load-secrets.outputs.CODEBERG }}
    steps:

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
  
      - name: Load credentials
        uses: 1password/load-secrets-action@v1
        id: op-load-secrets
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SETTINGS_LOCATION: "op://git/settings/${{github.event.inputs.repo}}"
          TOKEN: "op://git/GITHUB/TOKEN"
          PYPI_API_TOKEN: "op://git/PYPI_API_TOKEN/password"
          DOCKER_USERNAME: "op://git/DOCKERHUB/DOCKER_USERNAME"
          DOCKER_HUB_ACCESS_TOKEN: "op://git/DOCKERHUB/password"
          GITLAB: "op://git/GITLAB/key"
          CODEBERG: "op://git/CODEBERG/key"

      - id: step0
        run: echo ${{github.event.inputs.repo}}

      # - id: step0
      #   run: echo ${{ steps.op-load-secrets.outputs.SETTINGS_LOCATION }} >> $GITHUB_OUTPUT
      # - id: step1
      #   run: |
      #     echo ${{ steps.op-load-secrets.outputs.TOKEN }} >> $GITHUB_OUTPUT
      # - id: step2
      #   run: echo ${{ steps.op-load-secrets.outputs.PYPI_API_TOKEN }} >> $GITHUB_OUTPUT
      # - id: step3
      #   run: echo ${{ steps.op-load-secrets.outputs.DOCKER_USERNAME }} >> $GITHUB_OUTPUT
      # - id: step4
      #   run: echo ${{ steps.op-load-secrets.outputs.DOCKER_HUB_ACCESS_TOKEN }} >> $GITHUB_OUTPUT
      # - id: step5
      #   run: echo ${{ steps.op-load-secrets.outputs.GITLAB }} >> $GITHUB_OUTPUT
      # - id: step6
      #   run: echo ${{ steps.op-load-secrets.outputs.CODEBERG }} >> $GITHUB_OUTPUT
